### ISSUE TITLE
Support for Azure Pipelines for StrykerJS

### ISSUE THREAD

**Issue by andrelutza** [stryker-mutator/stryker-js#3494]
**Question**

Is there a way to integrate StrykerJS in an Azure CI Pipeline? We are needing it for an Angular project.

**Stryker environment**

```
+-- @stryker-mutator/core@5.6.1
+-- @stryker-mutator/karma-runner@5.6.1
```

```
+-- @angular/cli@13.0.4
+-- jasmine-core@3.10.1
+-- karma-chrome-launcher@3.1.1
+-- karma-coverage@2.0.3
+-- karma-jasmine-html-reporter@1.7.0
+-- karma-jasmine@4.0.2
+-- karma@6.3.19
+-- typescript@4.4.4
```

**Comment by nicojs** [comment]
Hi @andrelutza 🙋‍♂️

Sure you can. We're running it in a github workflow as well, see https://github.com/stryker-mutator/stryker-js/blob/master/.github/workflows/mutation-testing.yml

An example for azure devops:

```yml
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm run stryker
  displayName: 'npm install and run Stryker'
```
